services:
  js-flightservice:
    build:
      context: ./backend/FlightService
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true
    env_file:
      - ./backend/FlightService/.env
    ports:
      - "12877:12877"
    networks:
      - app-net

  js-frontend-book-flight-project:
    build:
      context: ./frontend-book-flight-project
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true
    env_file:
      - ./frontend-book-flight-project/.env
    ports:
      - "4173:4173"
    networks:
      - app-net
    depends_on:
      - js-flightservice

networks:
  app-net:
    driver: bridge
