services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: dbbookflight
      POSTGRES_USER: dbbookflight_user
      POSTGRES_PASSWORD: RjAfoKWWt0Zk7jG4atM9EdYfdvJiVuRy
    ports:
      - "5432:5432"
    networks:
      - app-net
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend/FlightService
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "12877:12877"
    environment:
      - PORT=12877
      - DATABASE_URL=postgresql://dbbookflight_user:RjAfoKWWt0Zk7jG4atM9EdYfdvJiVuRy@dpg-d0rl9nali9vc738n34b0-a.frankfurt-postgres.render.com/dbbookflight
    restart: unless-stopped
    init: true
    env_file:
      - ./backend/FlightService/.env
    networks:
      - app-net
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend-book-flight-project
      args:
        VITE_URL: http://localhost:12877
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_URL=http://localhost:5173
    restart: unless-stopped
    init: true
    env_file:
      - ./frontend-book-flight-project/.env
    networks:
      - app-net
    depends_on:
      - backend

networks:
  app-net:
    driver: bridge

volumes:
  db_data:
